//! Pre-accept Claude Code's Bypass-Permissions launch dialog.
//!
//! # The dialog
//!
//! Starting Claude Code with `--dangerously-skip-permissions` renders a
//! full-screen consent dialog before the TUI:
//!
//! ```text
//!   WARNING: Claude Code running in Bypass Permissions mode
//!   …
//! ❯ No, exit
//!   Yes, I accept
//!   Enter to confirm · Esc to cancel
//! ```
//!
//! Every harness-managed relaunch this daemon performs passes that flag, so
//! every relaunch can land on the dialog. That is hostile to an automated
//! restart: the dialog's cancel row renders the same `❯` glyph the idle-prompt
//! detector keys on, so the pane looks ready, the resume prompt gets typed
//! into the dialog, and the default-selected "No, exit" submits — Claude exits
//! and the prompt text spills into the bare pane shell (operator-observed on
//! Claude Code 2.1.251, 2026-08-29).
//!
//! # The persisted acceptance
//!
//! Accepting the dialog interactively records the acceptance in the user
//! settings file as a boolean key (`SETTINGS_KEY` below). Claude Code reads
//! that key from several settings tiers — the user file, the project-local
//! file, the `--settings <path>` file, and managed policy settings — and skips
//! the dialog when ANY of them has it set. Older builds recorded the
//! acceptance elsewhere and migrate it into this key on first run, so this is
//! the forward-compatible place to write it.
//!
//! Writing the key ourselves turns the dialog from "every relaunch" into
//! "never", which is why the relaunch paths call [`ensure_accepted`] before
//! they bring Claude back up. It is a best-effort optimisation, NOT a
//! guarantee: a settings tier we cannot see (managed policy) or a future
//! rename would bring the dialog back, so the relaunch paths still watch the
//! pane for it and accept it there. See
//! `tmux::bypass_permissions_dialog_visible`.
//!
//! # Write discipline
//!
//! The settings file belongs to the operator and is frequently
//! version-controlled, so this module does NOT round-trip it through a JSON
//! serializer (that would reorder keys and reflow the whole file, producing a
//! large spurious diff). It parses the file only to VALIDATE it and to check
//! whether the key is already set, then performs a surgical textual insert of
//! one line after the opening brace, re-parses the result, and refuses to
//! write anything that did not survive the re-parse. The write is atomic
//! (temp file in the same directory + rename).

use std::path::{Path, PathBuf};

/// The settings key Claude Code sets when a human accepts the
/// Bypass-Permissions dialog.
pub const SETTINGS_KEY: &str = "skipDangerousModePermissionPrompt";

/// What [`ensure_accepted`] did.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConsentWrite {
    /// The key was already set — nothing written.
    AlreadySet,
    /// The key was added to an existing settings file.
    Inserted,
    /// The settings file did not exist and was created.
    Created,
    /// Nothing was written and nothing is guaranteed: the file exists but is
    /// not something we are willing to edit (invalid JSON, or a top-level
    /// value that is not an object), or the write failed. The caller falls
    /// back to accepting the dialog on the pane.
    Skipped,
}

/// Resolve the settings files that should carry the acceptance.
///
/// * the user settings file — `$CLAUDE_CONFIG_DIR/settings.json` when that env
///   var is set, else `$HOME/.claude/settings.json`. This is the tier the
///   dialog itself writes.
/// * the `--settings <path>` file named by `CLAUDE_SHIM_SETTINGS_PATH`, when
///   set AND already present on disk. Relaunch argv built by
///   `policy::build_relaunch_claude_argv` passes that file with
///   `--setting-sources project,local`, which DROPS the user tier — so on that
///   deployment shape the user file alone would not suppress the dialog. Only
///   an existing file is touched: the shim is generated by the container
///   entrypoint and creating it here could mask a genuine startup failure.
pub fn settings_targets() -> Vec<PathBuf> {
    let mut targets = Vec::new();

    let user_dir = match std::env::var("CLAUDE_CONFIG_DIR") {
        Ok(dir) if !dir.is_empty() => Some(PathBuf::from(dir)),
        _ => std::env::var("HOME")
            .ok()
            .filter(|h| !h.is_empty())
            .map(|h| PathBuf::from(h).join(".claude")),
    };
    if let Some(dir) = user_dir {
        targets.push(dir.join("settings.json"));
    }

    if let Ok(shim) = std::env::var("CLAUDE_SHIM_SETTINGS_PATH") {
        let shim = PathBuf::from(shim);
        if !shim.as_os_str().is_empty() && shim.exists() && !targets.contains(&shim) {
            targets.push(shim);
        }
    }

    targets
}

/// Is the acceptance key already truthy in this settings text?
///
/// Only a literal `true` counts. A `false` value is a deliberate opt-out by
/// the operator and is left alone — the pane-side acceptance still handles the
/// dialog, so honouring the operator's `false` costs nothing.
pub(crate) fn already_accepted(text: &str) -> bool {
    serde_json::from_str::<serde_json::Value>(text)
        .ok()
        .and_then(|v| v.get(SETTINGS_KEY).and_then(|k| k.as_bool()))
        .unwrap_or(false)
}

/// Pure: plan the new contents of a settings file that should carry the
/// acceptance key.
///
/// Returns `None` when nothing should be written — the key is already `true`,
/// the operator explicitly set it to `false`, the text is not valid JSON, the
/// top level is not an object, or the surgical insert did not produce valid
/// JSON. Refusing is always safe: the caller falls back to accepting the
/// dialog on the pane.
pub(crate) fn plan_insert(text: &str) -> Option<String> {
    let value: serde_json::Value = serde_json::from_str(text).ok()?;
    let obj = value.as_object()?;
    // Present in any form (true or a deliberate false) -> leave it alone.
    if obj.contains_key(SETTINGS_KEY) {
        return None;
    }

    let inserted = if obj.is_empty() {
        // `{}` (possibly with whitespace): a textual insert after the brace
        // would leave a trailing comma, so emit a whole small object instead.
        format!("{{\n  \"{}\": true\n}}\n", SETTINGS_KEY)
    } else {
        let brace = text.find('{')?;
        let (head, tail) = text.split_at(brace + 1);
        format!("{}\n  \"{}\": true,{}", head, SETTINGS_KEY, tail)
    };

    // Never hand back something that does not parse.
    serde_json::from_str::<serde_json::Value>(&inserted).ok()?;
    Some(inserted)
}

/// Idempotently ensure the acceptance key is set in `path`.
///
/// Creates the file (and its parent directory) when absent. Never clobbers a
/// file it cannot parse. The write is atomic: a sibling temp file is written
/// and renamed over the target, so a crash mid-write cannot leave the operator
/// with a truncated settings file.
pub fn ensure_accepted(path: &Path) -> ConsentWrite {
    match std::fs::read_to_string(path) {
        Ok(text) => {
            if already_accepted(&text) {
                return ConsentWrite::AlreadySet;
            }
            match plan_insert(&text) {
                Some(updated) => {
                    if write_atomic(path, &updated) {
                        ConsentWrite::Inserted
                    } else {
                        ConsentWrite::Skipped
                    }
                }
                None => ConsentWrite::Skipped,
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            if let Some(parent) = path.parent() {
                if let Err(e) = std::fs::create_dir_all(parent) {
                    tracing::warn!(
                        error = %e,
                        dir = %parent.display(),
                        "bypass-consent: could not create settings dir"
                    );
                    return ConsentWrite::Skipped;
                }
            }
            let fresh = format!("{{\n  \"{}\": true\n}}\n", SETTINGS_KEY);
            if write_atomic(path, &fresh) {
                ConsentWrite::Created
            } else {
                ConsentWrite::Skipped
            }
        }
        Err(e) => {
            tracing::warn!(
                error = %e,
                path = %path.display(),
                "bypass-consent: could not read settings file"
            );
            ConsentWrite::Skipped
        }
    }
}

/// Ensure the acceptance key in every [`settings_targets`] file. Returns the
/// outcome per file, for logging.
pub fn ensure_accepted_everywhere() -> Vec<(PathBuf, ConsentWrite)> {
    settings_targets()
        .into_iter()
        .map(|p| {
            let outcome = ensure_accepted(&p);
            (p, outcome)
        })
        .collect()
}

/// Write `contents` to `path` via a sibling temp file + rename.
fn write_atomic(path: &Path, contents: &str) -> bool {
    let tmp = path.with_extension("claude-watch.tmp");
    if let Err(e) = std::fs::write(&tmp, contents) {
        tracing::warn!(
            error = %e,
            path = %tmp.display(),
            "bypass-consent: temp write failed"
        );
        return false;
    }
    if let Err(e) = std::fs::rename(&tmp, path) {
        tracing::warn!(
            error = %e,
            path = %path.display(),
            "bypass-consent: settings rename failed"
        );
        let _ = std::fs::remove_file(&tmp);
        return false;
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn already_accepted_reads_the_key() {
        assert!(already_accepted(
            r#"{"skipDangerousModePermissionPrompt": true}"#
        ));
        assert!(!already_accepted(
            r#"{"skipDangerousModePermissionPrompt": false}"#
        ));
        assert!(!already_accepted(r#"{"model": "opus"}"#));
        assert!(!already_accepted("not json"));
    }

    #[test]
    fn plan_insert_adds_the_key_and_keeps_everything_else_byte_for_byte() {
        let original = "{\n  \"model\": \"opus\",\n  \"env\": {\n    \"A\": \"1\"\n  }\n}\n";
        let updated = plan_insert(original).expect("should insert");
        assert!(updated.contains("\"skipDangerousModePermissionPrompt\": true,"));
        // Everything the operator had is still present, unreflowed.
        assert!(updated.contains("  \"model\": \"opus\",\n"));
        assert!(updated.contains("  \"env\": {\n    \"A\": \"1\"\n  }\n"));
        // And the result is still valid JSON with both keys.
        let v: serde_json::Value = serde_json::from_str(&updated).unwrap();
        assert_eq!(v[SETTINGS_KEY], serde_json::json!(true));
        assert_eq!(v["model"], serde_json::json!("opus"));
    }

    #[test]
    fn plan_insert_is_idempotent() {
        let already = r#"{"skipDangerousModePermissionPrompt": true, "model": "opus"}"#;
        assert_eq!(plan_insert(already), None);
    }

    #[test]
    fn plan_insert_respects_an_explicit_false() {
        let opted_out = r#"{"skipDangerousModePermissionPrompt": false}"#;
        assert_eq!(plan_insert(opted_out), None);
    }

    #[test]
    fn plan_insert_handles_an_empty_object() {
        let updated = plan_insert("{}").expect("should insert");
        let v: serde_json::Value = serde_json::from_str(&updated).unwrap();
        assert_eq!(v[SETTINGS_KEY], serde_json::json!(true));
    }

    #[test]
    fn plan_insert_refuses_non_json_and_non_objects() {
        assert_eq!(plan_insert("this is not json"), None);
        assert_eq!(plan_insert("[1, 2, 3]"), None);
        assert_eq!(plan_insert(""), None);
    }

    #[test]
    fn ensure_accepted_creates_then_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("nested").join("settings.json");

        assert_eq!(ensure_accepted(&path), ConsentWrite::Created);
        assert!(already_accepted(&std::fs::read_to_string(&path).unwrap()));

        assert_eq!(ensure_accepted(&path), ConsentWrite::AlreadySet);
    }

    #[test]
    fn ensure_accepted_inserts_into_an_existing_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        std::fs::write(&path, "{\n  \"model\": \"opus\"\n}\n").unwrap();

        assert_eq!(ensure_accepted(&path), ConsentWrite::Inserted);
        let text = std::fs::read_to_string(&path).unwrap();
        assert!(already_accepted(&text));
        assert!(text.contains("\"model\": \"opus\""));
        assert_eq!(ensure_accepted(&path), ConsentWrite::AlreadySet);
    }

    #[test]
    fn ensure_accepted_never_clobbers_an_unparseable_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        std::fs::write(&path, "{ this is broken,,, }").unwrap();

        assert_eq!(ensure_accepted(&path), ConsentWrite::Skipped);
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            "{ this is broken,,, }"
        );
    }
}
